### ISSUE TITLE
[FR][MAP] Expand support to geometry columns for map rendering

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/franchise#7]
As of today, the current version only shows the map option if the resulting table has `latitude`and `longitude` columns. 

So, we should add support CARTO format (`the_geom` column) and rendering of polygons and lines. This can be done using [GeoJSON](http://leafletjs.com/reference-1.2.0.html#geojson) (first iteration) layer or [MVT](http://leafletjs.com/plugins.html#vector-tiles) (future iterations)

**Comment by alrocar** [comment]
Adding support for carto.js -> https://github.com/CartoDB/franchise/tree/add_cartodbjs_support
